queue_rules:
  - name: vm2-draftbot-secret-chain
    batch_size: 1
    max_checks_retries: 1
    queue_conditions:
      - base = vm2-draftbot-chain-base-0915
      - title = VM2_DRAFTBOT_SECRET_CHAIN
    merge_conditions:
      - base = vm2-draftbot-chain-base-0915
      - title = VM2_DRAFTBOT_SECRET_CHAIN
      - check-success = vm2-draftbot-chain-hold
pull_request_rules: []
